import type {
  MachineSimulationSchema,
  MachineTypeId,
  SimulationParameterDefinition,
} from "@/lib/domain/types";

function defineParameters(
  parameters: SimulationParameterDefinition[],
): SimulationParameterDefinition[] {
  return parameters;
}

export const simulationSchemasByMachineType: Record<
  string,
  MachineSimulationSchema
> = {
  ai4i: {
    machineType: "ai4i",
    title: "AI4I Machine Scenario",
    description:
      "Configure AI4I telemetry-driven operating conditions for what-if analysis.",
    parameters: defineParameters([
      {
        key: "airTempK",
        label: "Air Temperature",
        type: "number",
        unit: "K",
        min: 285,
        max: 325,
        step: 0.1,
        defaultValue: 299.5,
        required: true,
        description: "Ambient air temperature for the AI4I operating scenario.",
        category: "Thermal",
        displayOrder: 10,
      },
      {
        key: "processTempK",
        label: "Process Temperature",
        type: "number",
        unit: "K",
        min: 290,
        max: 340,
        step: 0.1,
        defaultValue: 309.2,
        required: true,
        description:
          "Expected process temperature under current load conditions.",
        category: "Thermal",
        displayOrder: 20,
      },
      {
        key: "rotationalSpeed",
        label: "Rotational Speed",
        type: "number",
        unit: "rpm",
        min: 1100,
        max: 3000,
        step: 1,
        defaultValue: 1500,
        required: true,
        description: "Spindle rotational speed from AI4I telemetry profile.",
        category: "Mechanical",
        displayOrder: 30,
      },
      {
        key: "torque",
        label: "Torque",
        type: "number",
        unit: "Nm",
        min: 5,
        max: 90,
        step: 0.1,
        defaultValue: 40,
        required: true,
        description: "Expected spindle torque for the scenario.",
        category: "Mechanical",
        displayOrder: 40,
      },
      {
        key: "toolWear",
        label: "Tool Wear",
        type: "number",
        unit: "min",
        min: 0,
        max: 300,
        step: 1,
        defaultValue: 120,
        required: true,
        description: "Current tool wear state before simulation run.",
        category: "Fault / Wear Conditions",
        displayOrder: 50,
      },
      {
        key: "runtimeHours",
        label: "Simulation Horizon",
        type: "number",
        unit: "h",
        min: 1,
        max: 72,
        step: 1,
        defaultValue: 24,
        required: true,
        description: "Forecast window for projected risk and downtime.",
        category: "Load / Operating Conditions",
        displayOrder: 60,
      },
      {
        key: "productType",
        label: "Product Type",
        type: "select",
        defaultValue: "M",
        options: [
          { label: "Low (L)", value: "L" },
          { label: "Medium (M)", value: "M" },
          { label: "High (H)", value: "H" },
        ],
        description: "AI4I product variant affecting stress profile.",
        category: "Load / Operating Conditions",
        displayOrder: 70,
        advanced: true,
      },
      {
        key: "loadPercent",
        label: "Load Percent",
        type: "number",
        unit: "%",
        min: 20,
        max: 100,
        step: 1,
        defaultValue: 70,
        description: "Relative load used to stress AI4I operating conditions.",
        category: "Load / Operating Conditions",
        displayOrder: 80,
        advanced: true,
      },
    ]),
  },
  sensor: {
    machineType: "sensor",
    title: "Sensor Machine Scenario",
    description:
      "Configure machine-b sensor inputs from the time-series telemetry dataset.",
    parameters: defineParameters([
      {
        key: "temperature",
        label: "Temperature",
        type: "number",
        unit: "°C",
        min: 0,
        max: 120,
        step: 0.1,
        defaultValue: 72,
        required: true,
        description: "Baseline machine temperature for the scenario.",
        category: "Thermal",
        displayOrder: 10,
      },
      {
        key: "pressure",
        label: "Pressure",
        type: "number",
        unit: "bar",
        min: 0,
        max: 20,
        step: 0.1,
        defaultValue: 5.4,
        required: true,
        description: "Operating pressure from the machine-b profile.",
        category: "Load / Operating Conditions",
        displayOrder: 20,
      },
      {
        key: "vibrationLevel",
        label: "Vibration Level",
        type: "number",
        unit: "mm/s",
        min: 0,
        max: 25,
        step: 0.1,
        defaultValue: 3.1,
        required: true,
        description: "Measured vibration level in the selected window.",
        category: "Mechanical",
        displayOrder: 30,
      },
      {
        key: "humidity",
        label: "Humidity",
        type: "number",
        unit: "%",
        min: 10,
        max: 100,
        step: 1,
        defaultValue: 58,
        required: true,
        description: "Ambient humidity around machine-b.",
        category: "Environmental",
        displayOrder: 40,
      },
      {
        key: "powerConsumption",
        label: "Power Consumption",
        type: "number",
        unit: "kW",
        min: 0,
        max: 250,
        step: 0.1,
        defaultValue: 96,
        required: true,
        description: "Projected power draw in the simulation period.",
        category: "Electrical",
        displayOrder: 50,
      },
      {
        key: "runtimeHours",
        label: "Simulation Horizon",
        type: "number",
        unit: "h",
        min: 1,
        max: 72,
        step: 1,
        defaultValue: 12,
        required: true,
        description: "Forecast horizon for risk projection.",
        category: "Load / Operating Conditions",
        displayOrder: 60,
      },
      {
        key: "loadPercent",
        label: "Load Percent",
        type: "number",
        unit: "%",
        min: 20,
        max: 100,
        step: 1,
        defaultValue: 75,
        description: "Relative operational load applied to machine-b.",
        category: "Load / Operating Conditions",
        displayOrder: 70,
        advanced: true,
      },
      {
        key: "sensorNoise",
        label: "Sensor Noise",
        type: "number",
        unit: "%",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 18,
        description: "Estimated signal noise that can mask anomaly patterns.",
        category: "Fault / Wear Conditions",
        displayOrder: 80,
        advanced: true,
      },
      {
        key: "dutyCycle",
        label: "Duty Cycle",
        type: "select",
        defaultValue: "continuous",
        options: [
          { label: "Intermittent", value: "intermittent" },
          { label: "Continuous", value: "continuous" },
          { label: "Overloaded", value: "overloaded" },
        ],
        description: "Operational duty mode over the simulation horizon.",
        category: "Fault / Wear Conditions",
        displayOrder: 90,
        advanced: true,
      },
    ]),
  },
  "real-sensor": {
    machineType: "real-sensor",
    title: "Real Sensor Vibration Scenario",
    description:
      "Set high-frequency 3-axis vibration session conditions for machine-c.",
    parameters: defineParameters([
      {
        key: "vibrationX",
        label: "Vibration X",
        type: "number",
        unit: "g",
        min: -10,
        max: 10,
        step: 0.01,
        defaultValue: 0.32,
        required: true,
        description: "Primary axis vibration value for the session.",
        category: "Mechanical",
        displayOrder: 10,
      },
      {
        key: "vibrationY",
        label: "Vibration Y",
        type: "number",
        unit: "g",
        min: -10,
        max: 10,
        step: 0.01,
        defaultValue: 0.28,
        required: true,
        description: "Secondary axis vibration value for the session.",
        category: "Mechanical",
        displayOrder: 20,
      },
      {
        key: "vibrationZ",
        label: "Vibration Z",
        type: "number",
        unit: "g",
        min: -10,
        max: 10,
        step: 0.01,
        defaultValue: 0.41,
        required: true,
        description: "Vertical axis vibration value for the session.",
        category: "Mechanical",
        displayOrder: 30,
      },
      {
        key: "temperature",
        label: "Temperature",
        type: "number",
        unit: "°C",
        min: 0,
        max: 120,
        step: 0.1,
        defaultValue: 68,
        required: true,
        description: "Session temperature during vibration capture.",
        category: "Thermal",
        displayOrder: 40,
      },
      {
        key: "sessionDurationMinutes",
        label: "Session Duration",
        type: "number",
        unit: "min",
        min: 5,
        max: 480,
        step: 1,
        defaultValue: 60,
        required: true,
        description: "Duration of the high-frequency vibration window.",
        category: "Load / Operating Conditions",
        displayOrder: 50,
      },
      {
        key: "runtimeHours",
        label: "Simulation Horizon",
        type: "number",
        unit: "h",
        min: 1,
        max: 72,
        step: 1,
        defaultValue: 8,
        required: true,
        description: "Forecast horizon used for projected failure risk.",
        category: "Load / Operating Conditions",
        displayOrder: 60,
      },
      {
        key: "imbalanceIndex",
        label: "Imbalance Index",
        type: "number",
        unit: "%",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 30,
        description: "Estimated rotor imbalance severity.",
        category: "Fault / Wear Conditions",
        displayOrder: 70,
        advanced: true,
      },
      {
        key: "bearingCondition",
        label: "Bearing Condition",
        type: "select",
        defaultValue: "stable",
        options: [
          { label: "Stable", value: "stable" },
          { label: "Worn", value: "worn" },
          { label: "Critical", value: "critical" },
        ],
        description: "Bearing health estimate entering the scenario.",
        category: "Fault / Wear Conditions",
        displayOrder: 80,
        advanced: true,
      },
    ]),
  },
  "vibration-motor": {
    machineType: "ai4i",
    title: "AI4I Machine Scenario",
    description: "Legacy alias for AI4I simulation schema.",
    parameters: defineParameters([]),
  },
  "electric-motor": {
    machineType: "sensor",
    title: "Sensor Machine Scenario",
    description: "Legacy alias for sensor simulation schema.",
    parameters: defineParameters([]),
  },
  "packaging-drive": {
    machineType: "real-sensor",
    title: "Real Sensor Vibration Scenario",
    description: "Legacy alias for Machine C real-sensor simulation schema.",
    parameters: defineParameters([]),
  },
  kaggle: {
    machineType: "real-sensor",
    title: "Real Sensor Vibration Scenario",
    description: "Legacy alias for Machine C real-sensor simulation schema.",
    parameters: defineParameters([]),
  },
};

simulationSchemasByMachineType["vibration-motor"].parameters =
  simulationSchemasByMachineType.ai4i.parameters;
simulationSchemasByMachineType["electric-motor"].parameters =
  simulationSchemasByMachineType.sensor.parameters;
simulationSchemasByMachineType["packaging-drive"].parameters =
  simulationSchemasByMachineType["real-sensor"].parameters;
simulationSchemasByMachineType.kaggle.parameters =
  simulationSchemasByMachineType["real-sensor"].parameters;

export function getSimulationSchemaForMachineType(
  machineType: MachineTypeId | null | undefined,
) {
  if (!machineType) {
    return null;
  }

  return simulationSchemasByMachineType[machineType] ?? null;
}
